<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.juzi</groupId>
        <artifactId>chien</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>chien-admin</artifactId>
    <name>chien-admin</name>
    <description>Chien Admin - 启动模块（安全认证、通用组件）</description>

    <dependencies>
        <!-- chien-system 模块 -->
        <dependency>
            <groupId>com.juzi</groupId>
            <artifactId>chien-system</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- chien-log 日志模块 -->
        <dependency>
            <groupId>com.juzi</groupId>
            <artifactId>chien-log</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Spring Boot Actuator (项目监控配置) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- JWT -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.12.6</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
